apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Ledn-Demo-1
  region: ca-central-1

nodeGroups:
  - name: ledn-demo-ng
    minSize: 2
    maxSize: 5
    instancesDistribution: 
      maxPrice: 0.2
      instanceTypes: ["t2.small" , "t2.micro"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh:
      publicKeyName: ec2-user
      allow: true # To allow SSH

#cloudWatch: # Enable CloudWatch logging 
#  clusterLogging:
#    enableTypes: ["api" , "audit" , "authenticator"] #To enable all the five services, user ['*'] Controller Manager, Scheduler

# Cluster Config
  #- name: ng-1
  #  instanceType: t2.micro
  #  desiredCapacity: 2
  #  ssh:
  #    publicKeyName: ec2-user
  #    allow: true
