apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Ledn-Dev-01
  region: ca-central-1 # Canada Region

nodeGroups:
  - name: Ledn-Dev01
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: ec2-user
      allow: true # Allow SSH 

cloudWatch: # Enable CloudWatch logging 
  clusterLogging:
    enableTypes: ["api" , "audit" , "authenticator"] #To enable all the five services['*'] -  Controller Manager, Scheduler


# Can be enabled for spot instance
#nodeGroups:
#  - name: ledn-demo-ng
#    minSize: 2
#    maxSize: 5
#    instancesDistribution: 
#      maxPrice: 0.2
#      instanceTypes: ["t2.small" , "t2.micro"]
#      onDemandBaseCapacity: 0
#      onDemandPercentageAboveBaseCapacity: 50
#    ssh:
#      publicKeyName: ec2-user
#      allow: true # To allow SSH