Server 
{
  root /data/www; # Serving the Ledn image http://3.235.192.64/images/ledn-logo.png
  location / {
    try_files $uri $uri/ =404;
 }
 
 # serve any other image files from /data/images/
  location ~* \.(png|jpg|jpeg)$ {
    root /data/images/;
 }
}
