apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-autoscaler
spec: 
  selector: 
    matchLabels:
      run: nginx
      servicetier: Dev
      client: ledn
      autoscaler: Enabled
  replicas: 1
  template: 
    metadata:
      labels: 
        run: nginx
        servicetier: Dev
        client: ledn
        autoscaler: Enabled
    spec:
      containers:
        - name: nginx-autoscaler
          image: nginx
          ports:
          - containerPort: 80
      nodeSelector:
        nodegroup-type: stateful-cacentral1b