apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Ledn-Dev-Scale-1a
  region: ca-central-1

nodeGroups:
  - name: Ledn-Dev-Scale
    instanceType: t2.micro
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["ca-central-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-cacentrala
      instance-type: t2.micro
      client: ledn
    ssh: 
      publicKeyName: ec2-user
      allow: true
  - name: Ledn-Dev-Scale-1b
    instanceType: t2.micro
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["ca-central-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-cacentral1b
      instance-type: t2.micro #onDemand
      client: ledn
    ssh: # use existing EC2 key
      publicKeyName: ec2-user
      allow: true
  
  #stateless workload
  #- name: scale-spot
  #  desiredCapacity: 1
  #  maxSize: 10
  #  instancesDistribution:
  #    instanceTypes: ["t2.small", "t3.small"]
  #    onDemandBaseCapacity: 0
  #    onDemandPercentageAboveBaseCapacity: 0
  #  availabilityZones: ["us-east-1c", "us-east-1d"]
  #  iam:
  #    withAddonPolicies:
  #      autoScaler: true
  #  labels:
  #    nodegroup-type: stateless-workload
  #    instance-type: spot
  #  ssh: 
  #    publicKeyName: ec2us-user
  #    allow: true
#availabilityZones: ["us-east-1c", "us-east-1d"]